In [1]:
import pandas as pd

In [51]:
df_m=pd.read_csv('IMDb movies.csv', low_memory=False)
df_r=pd.read_csv('IMDb ratings.csv', low_memory=True)

In [52]:
df_m.head()

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,...,actors,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics
0,tt0000009,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,NaN,Alexander Black,...,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,5.9,154,NaN,NaN,NaN,NaN,1.0,2.0
1,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,NaN,Charles Tait,...,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,6.1,589,$ 2250,NaN,NaN,NaN,7.0,7.0
2,tt0001892,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,...,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,5.8,188,NaN,NaN,NaN,NaN,5.0,2.0
3,tt0002101,Cleopatra,Cleopatra,1912,1912-11-13,"Drama, History",100,USA,English,Charles L. Gaskill,...,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,5.2,446,$ 45000,NaN,NaN,NaN,25.0,3.0
4,tt0002130,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",...,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,7.0,2237,NaN,NaN,NaN,NaN,31.0,14.0

In [53]:
df_m.columns

Index(['imdb_title_id', 'title', 'original_title', 'year', 'date_published',
       'genre', 'duration', 'country', 'language', 'director', 'writer',
       'production_company', 'actors', 'description', 'avg_vote', 'votes',
       'budget', 'usa_gross_income', 'worlwide_gross_income', 'metascore',
       'reviews_from_users', 'reviews_from_critics'],
      dtype='object')

In [54]:
df_m= df_m[['imdb_title_id', 'title', 'year', 'genre', 'country', ]]
df_r=df_r[['imdb_title_id', 'total_votes', 'mean_vote']]

In [55]:
df_m.head()

,imdb_title_id,title,year,genre,country
0,tt0000009,Miss Jerry,1894,Romance,USA
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,Cleopatra,1912,"Drama, History",USA
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy

In [56]:
df_r.columns

Index(['imdb_title_id', 'total_votes', 'mean_vote'], dtype='object')

In [57]:
df1=pd.DataFrame({'id': ['A', 'B','C','D'],
                 'age': [18,20,21,20]},)
df2=pd.DataFrame({'id': ['E', 'F','G','H'],
                 'age': [19,22,23,17]})

In [58]:
df1

  id  age
0  A   18
1  B   20
2  C   21
3  D   20

In [59]:
df2

  id  age
0  E   19
1  F   22
2  G   23
3  H   17

In [60]:
pd.concat([df1,df2],ignore_index=True)

  id  age
0  A   18
1  B   20
2  C   21
3  D   20
4  E   19
5  F   22
6  G   23
7  H   17

In [61]:
df_ms=df_m.sample(frac=0.5)

In [62]:
df_ms.shape

(42928, 5)

In [63]:
pd.concat([df_m,df_ms])

,imdb_title_id,title,year,genre,country
0,tt0000009,Miss Jerry,1894,Romance,USA
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,Cleopatra,1912,"Drama, History",USA
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
83981,tt8246392,Furie,2019,"Horror, Thriller","France, Belgium"
32668,tt0139877,La balia,1999,Drama,Italy
59956,tt1607583,Shut Up and Kiss Me,2010,"Comedy, Romance",USA
75863,tt4827986,The Sense of an Ending,2017,"Drama, Mystery",UK
25058,tt0098732,Últimas imágenes del naufragio,1989,Drama,"Argentina, Spain"

In [64]:
print(df_m.shape)
print(df_r.shape)

(85855, 5)
(85855, 3)

In [65]:
df_m.set_index('imdb_title_id',inplace=True)
df_r.set_index('imdb_title_id',inplace=True)

In [66]:
con=pd.concat([df_m, df_r], axis=1)

In [67]:
con.shape

(85855, 6)

In [68]:
con

,title,year,genre,country,total_votes,mean_vote
imdb_title_id,,,,,,
tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...
tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8